version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  fastapi:
    build: .
    ports:
      - "8008:8008"
    environment:
      - APP_ENV=env
    depends_on:
      - rabbitmq

  celery_worker:
    build: .
    command: celery -A proj.celery_app worker --pool=solo --loglevel=info
    environment:
      - APP_ENV=env
    depends_on:
      - rabbitmq
      - fastapi

  celery_beat:
    build: .
    command: celery -A proj.celery_app beat
    environment:
      - APP_ENV=env
    depends_on:
      - rabbitmq
      - fastapi

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: